### ISSUE TITLE
Symmetry Mode Not Working

### ISSUE THREAD

**Issue by pap1723** [drewcassidy/KSP-Conformal-Decals#33]
When placing a decal, if you place it in symmetry mode, and use a selected image instead of the mission flag, only the placed decal uses the selected image. The opposite symmetry decal is the mission flag.

**Comment by dnnp2011** [comment]
Having this problem as well

**Comment by drewcassidy** [comment]
Yeah I'm aware of the fix. I was actually in the middle of a refactor that would make the event flows a lot less spaghetti, but then I got burnt out on KSP stuff, and then I started a new job. And here we are a year later. I'll take a look at it soon

**Comment by drewcassidy** [comment]
@pap1723 Hey I'm not able to reproduce this issue. Can you write some detailed recreation instructions and post them in #36 

@dnnp2011 
> However, [`OnStart()` and `OnLoad()` only call `SetFlag()`](https://github.com/drewcassidy/KSP-Conformal-Decals/blob/a91a83a28019a0750eece152305f4b8c3ee60b82/Source/ConformalDecals/ModuleConformalFlag.cs#L48-L53), not `SetFlagSymmetryCounterparts()`.

actually this is fine! OnStart and OnLoad get called for every module, so updating the symmetry counterparts is redundant since they're guaranteed to get the same call
